### ISSUE TITLE
Links to not existing release notes release notes

### ISSUE THREAD

**Issue by Traumflug** [thirtybees/docs#69]
On page https://thirtybees.com/download/ release notes for version 1.0.4...1.0.6 link to a wiki page which covers release notes for 1.0.0...1.0.3, only.

Release notes for the more recent versions are here:

https://github.com/thirtybees/thirtybees/releases/tag/1.0.4
https://github.com/thirtybees/thirtybees/releases/tag/1.0.5
https://github.com/thirtybees/thirtybees/releases/tag/1.0.6

**Comment by Dh42** [comment]
Fixed
